-- Safe_Traders
-- Author: Ben
-- DateCreated: 8/19/2020 4:10:47 PM
--------------------------------------------------------------

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
	('TRADER_IMMUNITY_LAND', 'MODIFIER_PLAYER_UNIT_ADJUST_TRADE_ROUTE_PLUNDER_IMMUNITY'),
    ('TRADER_IMMUNITY_SEA', 'MODIFIER_PLAYER_UNIT_ADJUST_TRADE_ROUTE_PLUNDER_IMMUNITY');
INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('TRADER_GRANT_ABILITIES', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', NULL);

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('TRADER_GRANT_ABILITIES', 'AbilityType', 'ABILITY_TRADER_PLUNDER_IMMUNITY'),
    ('TRADER_IMMUNITY_LAND', 'DomainType', 'DOMAIN_LAND'),
    ('TRADER_IMMUNITY_SEA', 'DomainType', 'DOMAIN_SEA');

INSERT INTO Types(Type, Kind) VALUES
    ('ABILITY_TRADER_PLUNDER_IMMUNITY', 'KIND_ABILITY');

INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive) VALUES
    ('ABILITY_TRADER_PLUNDER_IMMUNITY', NULL, NULL, 0);
INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
    ('ABILITY_TRADER_PLUNDER_IMMUNITY', 'TRADER_IMMUNITY_LAND'),
    ('ABILITY_TRADER_PLUNDER_IMMUNITY', 'TRADER_IMMUNITY_SEA');
INSERT INTO TypeTags(Type, Tag) VALUES
    ('ABILITY_TRADER_PLUNDER_IMMUNITY', 'CLASS_TRADER');

